# Generated by Django 6.1.1 on 2026-09-13 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='niveau',
            name='cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='niveaux', to='programme.cycle'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='matiere',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='programme.matiere'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='programme.niveau'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='programmes', to='programme.serie'),
        ),
        migrations.AlterField(
            model_name='serie',
            name='niveau',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='series', to='programme.niveau'),
        ),
    ]
