# Generated by Django 6.1.1 on 2026-09-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0002_alter_niveau_cycle_alter_programme_matiere_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecon',
            old_name='prerequis',
            new_name='prerequis_lecons',
        ),
        migrations.AddField(
            model_name='lecon',
            name='a_retenir',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='lecon',
            name='prerequis_texte',
            field=models.TextField(blank=True, default=''),
        ),
    ]
