# Generated by Django 6.1.1 on 2026-09-14 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0003_rename_prerequis_lecon_prerequis_lecons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecon',
            name='histoire',
            field=models.TextField(blank=True, default=''),
        ),
    ]
