# Generated by Django 6.1.1 on 2026-09-14 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0004_lecon_histoire'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermeGlossaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terme', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('definition', models.TextField()),
                ('exemple', models.TextField(blank=True, default='')),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('lecon_liee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='termes_glossaire', to='programme.lecon')),
            ],
            options={
                'ordering': ['terme'],
            },
        ),
    ]
