# Generated by Django 6.1.1 on 2026-09-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0005_termeglossaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharteNotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(default='Charte de notation', max_length=255)),
                ('contenu', models.TextField(help_text="Markdown. Injecté tel quel dans le prompt système envoyé à l'IA.")),
                ('active', models.BooleanField(default=True, help_text="Une seule charte active à la fois : l'activer désactive les autres.")),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'charte de notation',
                'verbose_name_plural': 'chartes de notation',
                'ordering': ['-modifie_le'],
            },
        ),
    ]
