# Generated by Django 6.1.1 on 2026-09-21 19:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0007_charte_notation_amorce'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromptSectionNotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=20)),
                ('texte', models.TextField()),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('notion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompts_personnalises', to='programme.notion')),
            ],
            options={
                'verbose_name': 'prompt personnalisé',
                'verbose_name_plural': 'prompts personnalisés',
                'ordering': ['notion_id', 'section'],
                'unique_together': {('notion', 'section')},
            },
        ),
    ]
