# Generated by Django 6.1.1 on 2026-09-22 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0008_promptsectionnotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecon',
            name='sujet_examen',
            field=models.TextField(blank=True, default=''),
        ),
    ]
