# Generated by Django 6.1.1 on 2026-09-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programme', '0009_lecon_sujet_examen'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecon',
            name='est_gratuit',
            field=models.BooleanField(default=False, help_text='Accessible sans abonnement. Indépendant du statut de publication.', verbose_name='cours gratuit'),
        ),
    ]
