# Generated by Django 6.1.1 on 2026-09-12 17:37

import comptes.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('programme', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('telephone', models.CharField(help_text='Format attendu : +227 suivi de 8 chiffres.', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format +227 suivi de 8 chiffres (ex. +22790000000).', regex='^\\+227\\d{8}$')], verbose_name='téléphone')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('prenom', models.CharField(max_length=100, verbose_name='prénom')),
                ('nom', models.CharField(max_length=100, verbose_name='nom')),
                ('role', models.CharField(choices=[('eleve', 'Élève'), ('enseignant', 'Enseignant'), ('admin', 'Admin'), ('partenaire', 'Partenaire')], default='eleve', max_length=20, verbose_name='rôle')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('actif', 'Actif'), ('rejete', 'Rejeté'), ('suspendu', 'Suspendu')], default='en_attente', max_length=20, verbose_name='statut')),
                ('is_active', models.BooleanField(default=True, verbose_name='actif')),
                ('is_staff', models.BooleanField(default=False, verbose_name='accès admin')),
                ('date_inscription', models.DateTimeField(auto_now_add=True, verbose_name="date d'inscription")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('niveau', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves', to='programme.niveau', verbose_name='niveau')),
                ('serie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eleves', to='programme.serie', verbose_name='série')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'utilisateur',
                'verbose_name_plural': 'utilisateurs',
                'ordering': ['-date_inscription'],
            },
            managers=[
                ('objects', comptes.models.UserManager()),
            ],
        ),
    ]
