# Generated by Django 6.1.1 on 2026-09-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='motif_rejet',
            field=models.TextField(blank=True, null=True, verbose_name='motif du rejet'),
        ),
    ]
