# Generated by Django 6.1.1 on 2026-09-13 07:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0002_user_motif_rejet'),
        ('programme', '0002_alter_niveau_cycle_alter_programme_matiere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='niveau',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='programme.niveau', verbose_name='niveau'),
        ),
        migrations.AlterField(
            model_name='user',
            name='serie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='eleves', to='programme.serie', verbose_name='série'),
        ),
    ]
