# Generated by Django 6.1.1 on 2026-09-13 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0003_alter_user_niveau_alter_user_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='doit_changer_mdp',
            field=models.BooleanField(default=False, verbose_name='doit changer son mot de passe'),
        ),
    ]
