# Generated by Django 6.1.1 on 2026-09-24 14:58

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0004_user_doit_changer_mdp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_naissance',
            field=models.DateField(blank=True, null=True, verbose_name='date de naissance'),
        ),
        migrations.AddField(
            model_name='user',
            name='ecole',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='établissement scolaire'),
        ),
        migrations.AddField(
            model_name='user',
            name='genre',
            field=models.CharField(blank=True, choices=[('F', 'Féminin'), ('M', 'Masculin'), ('autre', 'Autre')], max_length=10, null=True, verbose_name='genre'),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='photo de profil'),
        ),
        migrations.AddField(
            model_name='user',
            name='ville',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ville'),
        ),
    ]
