# Generated by Django 6.1.1 on 2026-09-25 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0005_user_date_naissance_user_ecole_user_genre_user_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='abonnement_actif_jusqu_au',
            field=models.DateField(blank=True, help_text="Date de fin de l'abonnement en cours. Vide = jamais abonné.", null=True, verbose_name="abonnement actif jusqu'au"),
        ),
    ]
