# Generated by Django 6.1.1 on 2026-09-25 10:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0006_user_abonnement_actif_jusqu_au'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteFahimta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=17, unique=True, verbose_name='code')),
                ('duree_jours', models.PositiveIntegerField(default=30, help_text="Nombre de jours d'abonnement crédités à l'activation.", verbose_name='durée (jours)')),
                ('statut', models.CharField(choices=[('active', 'Active'), ('utilisee', 'Utilisée')], default='active', max_length=10, verbose_name='statut')),
                ('date_activation', models.DateTimeField(blank=True, null=True, verbose_name="date d'activation")),
                ('lot', models.CharField(db_index=True, max_length=64, verbose_name='lot')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='créée le')),
                ('utilisee_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartes_activees', to=settings.AUTH_USER_MODEL, verbose_name='activée par')),
            ],
            options={
                'verbose_name': 'carte Fahimta',
                'verbose_name_plural': 'cartes Fahimta',
                'ordering': ['-date_creation'],
            },
        ),
    ]
