# Generated by Django 6.1.1 on 2026-09-25 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0007_cartefahimta'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartefahimta',
            name='commission_figee',
            field=models.PositiveIntegerField(blank=True, help_text="Commission du vendeur au moment de l'assignation de cette carte.", null=True, verbose_name='commission figée (FCFA)'),
        ),
        migrations.AddField(
            model_name='cartefahimta',
            name='date_assignation',
            field=models.DateTimeField(blank=True, null=True, verbose_name="date d'assignation"),
        ),
        migrations.AddField(
            model_name='cartefahimta',
            name='vendeur',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'vendeur'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartes_assignees', to=settings.AUTH_USER_MODEL, verbose_name='vendeur'),
        ),
        migrations.AddField(
            model_name='user',
            name='commission_fcfa',
            field=models.PositiveIntegerField(default=0, help_text='Commission fixe par carte vendue — utilisée uniquement pour les vendeurs.', verbose_name='commission (FCFA)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('eleve', 'Élève'), ('enseignant', 'Enseignant'), ('admin', 'Admin'), ('partenaire', 'Partenaire'), ('vendeur', 'Vendeur')], default='eleve', max_length=20, verbose_name='rôle'),
        ),
    ]
