# Generated by Django 6.1.1 on 2026-09-25 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0008_cartefahimta_commission_figee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartefahimta',
            name='attribuee_a',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'eleve'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cartes_recues', to=settings.AUTH_USER_MODEL, verbose_name='attribuée à'),
        ),
        migrations.AddField(
            model_name='cartefahimta',
            name='date_attribution',
            field=models.DateTimeField(blank=True, null=True, verbose_name="date d'attribution"),
        ),
    ]
