# Generated by Django 6.1.1 on 2026-09-25 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0009_cartefahimta_attribuee_a_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ecole_ou_point_vente',
            field=models.CharField(blank=True, help_text='Repère physique du vendeur (école, boutique, marché…).', max_length=150, null=True, verbose_name='école ou point de vente'),
        ),
        migrations.AddField(
            model_name='user',
            name='quartier',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='quartier'),
        ),
    ]
