# Generated by Django 6.1.1 on 2026-09-25 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0010_user_ecole_ou_point_vente_user_quartier'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaiementNita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=20, verbose_name='téléphone')),
                ('montant', models.PositiveIntegerField(verbose_name='montant (FCFA)')),
                ('duree_jours', models.PositiveIntegerField(verbose_name='durée (jours)')),
                ('request_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='request ID')),
                ('reference_nita', models.CharField(blank=True, help_text="Connue seulement après la création de l'achat côté NITA.", max_length=64, null=True, verbose_name='référence NITA')),
                ('statut', models.CharField(choices=[('en_attente', 'En attente'), ('confirme', 'Confirmé'), ('echoue', 'Échoué')], default='en_attente', max_length=12, verbose_name='statut')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='créé le')),
                ('date_confirmation', models.DateTimeField(blank=True, null=True, verbose_name='confirmé le')),
                ('user', models.ForeignKey(limit_choices_to={'role': 'eleve'}, on_delete=django.db.models.deletion.CASCADE, related_name='paiements_nita', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'paiement NITA',
                'verbose_name_plural': 'paiements NITA',
                'ordering': ['-date_creation'],
            },
        ),
    ]
