# Generated by Django 6.1.1 on 2026-09-25 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comptes', '0011_paiementnita'),
    ]

    operations = [
        migrations.CreateModel(
            name='RappelAbonnementEnvoye',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seuil_jours', models.PositiveIntegerField(verbose_name='seuil (jours)')),
                ('date_expiration_visee', models.DateField(verbose_name='échéance visée')),
                ('date_envoi', models.DateTimeField(auto_now_add=True, verbose_name='envoyé le')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rappels_abonnement_envoyes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "rappel d'abonnement envoyé",
                'verbose_name_plural': "rappels d'abonnement envoyés",
                'ordering': ['-date_envoi'],
                'constraints': [models.UniqueConstraint(fields=('user', 'seuil_jours', 'date_expiration_visee'), name='unique_rappel_abonnement_par_seuil_et_echeance')],
            },
        ),
    ]
